#
# Module manifest for module 'ollama-powershell'
#
# Generated by: JamesBrundage
#
# Generated on: 3/1/2025
#

@{
    RootModule = 'ollama-powershell.psm1'
    ModuleVersion = '0.0.1'
    GUID = 'e9b68160-0f70-4821-86c5-64ddb66e841c'
    Author = 'JamesBrundage'
    CompanyName = 'Start-Automating'

    # Copyright statement for this module
    Copyright = '2025 Start-Automating'

    TypesToProcess = @('ollama-powershell.types.ps1xml')
    FormatsToProcess = @('ollama-powershell.format.ps1xml')

    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('AI','ollama', 'PowerShell', 'LLM')                    

            # A URL to the license for this module.
            LicenseURI = 'https://github.com/StartAutomating/ollama-powershell/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectURI = 'https://github.com/StartAutomating/ollama-powershell'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        }
    }

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

